const TOKEN_ASYNC_STORAGE_KEY = 'token';
const EMAIL_ASYNC_STORAGE_KEY = 'email';
const PASSWORD_ASYNC_STORAGE_KEY = 'password';

export {
  TOKEN_ASYNC_STORAGE_KEY,
  EMAIL_ASYNC_STORAGE_KEY,
  PASSWORD_ASYNC_STORAGE_KEY,
};
