const HTTP_STATUSES = {
  SUCCESS: 200,
  INVALID_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  REQUEST_TIMEOUT: 408,
  TEAPOT: 418,
  INVALID_DATA_PROVIDED: 422,
  SERVER_ERROR: 500,
};

const HTTP_HEADERS = {
  ACCEPT: 'Accept',
  CONTENT_TYPE: 'Content-Type',
  USER_LOCATION: 'X-User-Location',
  AUTHORIZATION: 'Authorization',
};

const HTTP_METHODS = {
  GET: 'GET',
  POST: 'POST',
  PUT: 'PUT',
  DELETE: 'DELETE',
  PATCH: 'PATCH',
};

const HTTP_CONTENT_TYPES = {
  JSON: 'application/json',
  FORM_DATA: 'multipart/form-data',
};

export {HTTP_STATUSES, HTTP_CONTENT_TYPES, HTTP_HEADERS, HTTP_METHODS};
