/*
  The folder will contain reusable constant values shared among different components
  Separate file for each entity would be created: constants/api.js, constants/journals.js, etc

  Important: each reusable constant should be named in UPPER_CASE
*/

export {
  NOOP,
  NOTIFICATION_TIMEOUT_IN_MS_SHORT,
  NOTIFICATION_TIMEOUT_IN_MS,
  DEFAULT_USER_IMAGE_DIMENSION,
  NUMBER_OF_LINES_IN_MULTILINE_TEXT_TINY,
  NUMBER_OF_LINES_IN_MULTILINE_TEXT_SHORT,
  NUMBER_OF_LINES_IN_MULTILINE_TEXT_MEDIUM,
  NUMBER_OF_ITEMS_ON_SINGLE_PAGE,
  MAX_NUMBER_OF_ITEMS_TO_RENDER_PER_BATCH,
  NUMBER_OF_COMMENT_REPLIES_SHOWN_BY_DEFAULT,
  NUMBER_OF_COMMENT_REPLIES_ON_SINGLE_PAGE,
  UNREAD_MESSAGES_CHECK_INTERVAL_IN_MS,
  COUNTRY_CODES,
} from './common';

export {ABOUT_ENDPOINTS} from './endpoints';

export {DEV_API_URL, PROD_API_URL} from './api';

export {
  HTTP_STATUSES,
  HTTP_CONTENT_TYPES,
  HTTP_HEADERS,
  HTTP_METHODS,
} from './http';

export {
  INITIAL_STATE,
  PENDING_STATE,
  REJECTED_STATE,
  FULFILLED_STATE,
  STORE_NAMES,
} from './store';

export {
  GET_REGEXP_BY_FIELD_TYPE,
  GET_MAX_LENGTH_BY_FIELD_TYPE,
  GET_KEYBOARD_TYPE_BY_FIELD_TYPE,
  ANY_FIELD,
  EMAIL_FIELD,
  PASSWORD_FIELD,
  PHONE_NUMBER_FIELD,
  DOI_FIELD,
  TEXT_FIELD_SHORT,
  TEXT_FIELD_MEDIUM,
  TEXT_FIELD_NORMAL,
  TEXT_FIELD_LONG,
  TEXT_FIELD_MAX_LONG,
  TEXT_WITH_NUMBERS_FIELD_SHORT,
  TEXT_WITH_NUMBERS_FIELD_MEDIUM,
  TEXT_WITH_NUMBERS_FIELD_NORMAL,
  TEXT_WITH_NUMBERS_FIELD_LONG,
  TEXT_WITH_NUMBERS_FIELD_MEDIUM_LONG,
  TEXT_WITH_NUMBERS_FIELD_MAX_LONG,
  URL_FIELD,
  ORCID_FIELD,
  INPUT_TYPES,
} from './validation';

export {TOKEN_ASYNC_STORAGE_KEY} from './asyncStorage';
