const COUNTRIES = [
  {id: 4, name: 'Afghanistan'},
  {id: 248, name: '\u00c5land Islands'},
  {id: 8, name: 'Albania'},
  {id: 12, name: 'Algeria'},
  {id: 16, name: 'American Samoa'},
  {id: 20, name: 'Andorra'},
  {id: 24, name: 'Angola'},
  {id: 660, name: 'Anguilla'},
  {id: 10, name: 'Antarctica'},
  {id: 28, name: 'Antigua and Barbuda'},
  {id: 32, name: 'Argentina'},
  {id: 51, name: 'Armenia'},
  {id: 533, name: 'Aruba'},
  {id: 36, name: 'Australia'},
  {id: 40, name: 'Austria'},
  {id: 31, name: 'Azerbaijan'},
  {id: 44, name: 'Bahamas'},
  {id: 48, name: 'Bahrain'},
  {id: 50, name: 'Bangladesh'},
  {id: 52, name: 'Barbados'},
  {id: 112, name: 'Belarus'},
  {id: 56, name: 'Belgium'},
  {id: 84, name: 'Belize'},
  {id: 204, name: 'Benin'},
  {id: 60, name: 'Bermuda'},
  {id: 64, name: 'Bhutan'},
  {id: 68, name: 'Bolivia, Plurinational State of'},
  {id: 535, name: 'Bonaire, Sint Eustatius and Saba'},
  {id: 70, name: 'Bosnia and Herzegovina'},
  {id: 72, name: 'Botswana'},
  {id: 74, name: 'Bouvet Island'},
  {id: 76, name: 'Brazil'},
  {id: 86, name: 'British Indian Ocean Territory'},
  {id: 96, name: 'Brunei Darussalam'},
  {id: 100, name: 'Bulgaria'},
  {id: 854, name: 'Burkina Faso'},
  {id: 108, name: 'Burundi'},
  {id: 116, name: 'Cambodia'},
  {id: 120, name: 'Cameroon'},
  {id: 124, name: 'Canada'},
  {id: 132, name: 'Cape Verde'},
  {id: 136, name: 'Cayman Islands'},
  {id: 140, name: 'Central African Republic'},
  {id: 148, name: 'Chad'},
  {id: 152, name: 'Chile'},
  {id: 156, name: 'China'},
  {id: 162, name: 'Christmas Island'},
  {id: 166, name: 'Cocos (Keeling) Islands'},
  {id: 170, name: 'Colombia'},
  {id: 174, name: 'Comoros'},
  {id: 178, name: 'Congo'},
  {id: 180, name: 'Congo, the Democratic Republic of the'},
  {id: 184, name: 'Cook Islands'},
  {id: 188, name: 'Costa Rica'},
  {id: 384, name: "C\u00f4te d'Ivoire"},
  {id: 191, name: 'Croatia'},
  {id: 192, name: 'Cuba'},
  {id: 531, name: 'Cura\u00e7ao'},
  {id: 196, name: 'Cyprus'},
  {id: 203, name: 'Czech Republic'},
  {id: 208, name: 'Denmark'},
  {id: 262, name: 'Djibouti'},
  {id: 212, name: 'Dominica'},
  {id: 214, name: 'Dominican Republic'},
  {id: 218, name: 'Ecuador'},
  {id: 818, name: 'Egypt'},
  {id: 222, name: 'El Salvador'},
  {id: 226, name: 'Equatorial Guinea'},
  {id: 232, name: 'Eritrea'},
  {id: 233, name: 'Estonia'},
  {id: 231, name: 'Ethiopia'},
  {id: 238, name: 'Falkland Islands (Malvinas)'},
  {id: 234, name: 'Faroe Islands'},
  {id: 242, name: 'Fiji'},
  {id: 246, name: 'Finland'},
  {id: 250, name: 'France'},
  {id: 254, name: 'French Guiana'},
  {id: 258, name: 'French Polynesia'},
  {id: 260, name: 'French Southern Territories'},
  {id: 266, name: 'Gabon'},
  {id: 270, name: 'Gambia'},
  {id: 268, name: 'Georgia'},
  {id: 276, name: 'Germany'},
  {id: 288, name: 'Ghana'},
  {id: 292, name: 'Gibraltar'},
  {id: 300, name: 'Greece'},
  {id: 304, name: 'Greenland'},
  {id: 308, name: 'Grenada'},
  {id: 312, name: 'Guadeloupe'},
  {id: 316, name: 'Guam'},
  {id: 320, name: 'Guatemala'},
  {id: 831, name: 'Guernsey'},
  {id: 324, name: 'Guinea'},
  {id: 624, name: 'Guinea-Bissau'},
  {id: 328, name: 'Guyana'},
  {id: 332, name: 'Haiti'},
  {id: 334, name: 'Heard Island and McDonald Islands'},
  {id: 336, name: 'Holy See (Vatican City State)'},
  {id: 340, name: 'Honduras'},
  {id: 344, name: 'Hong Kong'},
  {id: 348, name: 'Hungary'},
  {id: 352, name: 'Iceland'},
  {id: 356, name: 'India'},
  {id: 360, name: 'Indonesia'},
  {id: 364, name: 'Iran, Islamic Republic of'},
  {id: 368, name: 'Iraq'},
  {id: 372, name: 'Ireland'},
  {id: 833, name: 'Isle of Man'},
  {id: 376, name: 'Israel'},
  {id: 380, name: 'Italy'},
  {id: 388, name: 'Jamaica'},
  {id: 392, name: 'Japan'},
  {id: 832, name: 'Jersey'},
  {id: 400, name: 'Jordan'},
  {id: 398, name: 'Kazakhstan'},
  {id: 404, name: 'Kenya'},
  {id: 296, name: 'Kiribati'},
  {id: 408, name: "Korea, Democratic People's Republic of"},
  {id: 410, name: 'Korea, Republic of'},
  {id: 414, name: 'Kuwait'},
  {id: 417, name: 'Kyrgyzstan'},
  {id: 418, name: "Lao People's Democratic Republic"},
  {id: 428, name: 'Latvia'},
  {id: 422, name: 'Lebanon'},
  {id: 426, name: 'Lesotho'},
  {id: 430, name: 'Liberia'},
  {id: 434, name: 'Libya'},
  {id: 438, name: 'Liechtenstein'},
  {id: 440, name: 'Lithuania'},
  {id: 442, name: 'Luxembourg'},
  {id: 446, name: 'Macao'},
  {id: 807, name: 'Macedonia, the former Yugoslav Republic of'},
  {id: 450, name: 'Madagascar'},
  {id: 454, name: 'Malawi'},
  {id: 458, name: 'Malaysia'},
  {id: 462, name: 'Maldives'},
  {id: 466, name: 'Mali'},
  {id: 470, name: 'Malta'},
  {id: 584, name: 'Marshall Islands'},
  {id: 474, name: 'Martinique'},
  {id: 478, name: 'Mauritania'},
  {id: 480, name: 'Mauritius'},
  {id: 175, name: 'Mayotte'},
  {id: 484, name: 'Mexico'},
  {id: 583, name: 'Micronesia, Federated States of'},
  {id: 498, name: 'Moldova, Republic of'},
  {id: 492, name: 'Monaco'},
  {id: 496, name: 'Mongolia'},
  {id: 499, name: 'Montenegro'},
  {id: 500, name: 'Montserrat'},
  {id: 504, name: 'Morocco'},
  {id: 508, name: 'Mozambique'},
  {id: 104, name: 'Myanmar'},
  {id: 516, name: 'Namibia'},
  {id: 520, name: 'Nauru'},
  {id: 524, name: 'Nepal'},
  {id: 528, name: 'Netherlands'},
  {id: 540, name: 'New Caledonia'},
  {id: 554, name: 'New Zealand'},
  {id: 558, name: 'Nicaragua'},
  {id: 562, name: 'Niger'},
  {id: 566, name: 'Nigeria'},
  {id: 570, name: 'Niue'},
  {id: 574, name: 'Norfolk Island'},
  {id: 580, name: 'Northern Mariana Islands'},
  {id: 578, name: 'Norway'},
  {id: 512, name: 'Oman'},
  {id: 586, name: 'Pakistan'},
  {id: 585, name: 'Palau'},
  {id: 275, name: 'Palestinian Territory, Occupied'},
  {id: 591, name: 'Panama'},
  {id: 598, name: 'Papua New Guinea'},
  {id: 600, name: 'Paraguay'},
  {id: 604, name: 'Peru'},
  {id: 608, name: 'Philippines'},
  {id: 612, name: 'Pitcairn'},
  {id: 616, name: 'Poland'},
  {id: 620, name: 'Portugal'},
  {id: 630, name: 'Puerto Rico'},
  {id: 634, name: 'Qatar'},
  {id: 638, name: 'R\u00e9union'},
  {id: 642, name: 'Romania'},
  {id: 643, name: 'Russian Federation'},
  {id: 646, name: 'Rwanda'},
  {id: 652, name: 'Saint Barth\u00e9lemy'},
  {id: 654, name: 'Saint Helena, Ascension and Tristan da Cunha'},
  {id: 659, name: 'Saint Kitts and Nevis'},
  {id: 662, name: 'Saint Lucia'},
  {id: 663, name: 'Saint Martin (French part)'},
  {id: 666, name: 'Saint Pierre and Miquelon'},
  {id: 670, name: 'Saint Vincent and the Grenadines'},
  {id: 882, name: 'Samoa'},
  {id: 674, name: 'San Marino'},
  {id: 678, name: 'Sao Tome and Principe'},
  {id: 682, name: 'Saudi Arabia'},
  {id: 686, name: 'Senegal'},
  {id: 688, name: 'Serbia'},
  {id: 690, name: 'Seychelles'},
  {id: 694, name: 'Sierra Leone'},
  {id: 702, name: 'Singapore'},
  {id: 534, name: 'Sint Maarten (Dutch part)'},
  {id: 703, name: 'Slovakia'},
  {id: 705, name: 'Slovenia'},
  {id: 90, name: 'Solomon Islands'},
  {id: 706, name: 'Somalia'},
  {id: 710, name: 'South Africa'},
  {id: 239, name: 'South Georgia and the South Sandwich Islands'},
  {id: 728, name: 'South Sudan'},
  {id: 724, name: 'Spain'},
  {id: 144, name: 'Sri Lanka'},
  {id: 729, name: 'Sudan'},
  {id: 740, name: 'Suriname'},
  {id: 744, name: 'Svalbard and Jan Mayen'},
  {id: 748, name: 'Swaziland'},
  {id: 752, name: 'Sweden'},
  {id: 756, name: 'Switzerland'},
  {id: 760, name: 'Syrian Arab Republic'},
  {id: 158, name: 'Taiwan, Province of China'},
  {id: 762, name: 'Tajikistan'},
  {id: 834, name: 'Tanzania, United Republic of'},
  {id: 764, name: 'Thailand'},
  {id: 626, name: 'Timor-Leste'},
  {id: 768, name: 'Togo'},
  {id: 772, name: 'Tokelau'},
  {id: 776, name: 'Tonga'},
  {id: 780, name: 'Trinidad and Tobago'},
  {id: 788, name: 'Tunisia'},
  {id: 792, name: 'Turkey'},
  {id: 795, name: 'Turkmenistan'},
  {id: 796, name: 'Turks and Caicos Islands'},
  {id: 798, name: 'Tuvalu'},
  {id: 800, name: 'Uganda'},
  {id: 804, name: 'Ukraine'},
  {id: 784, name: 'United Arab Emirates'},
  {id: 826, name: 'United Kingdom'},
  {id: 840, name: 'United States'},
  {id: 581, name: 'United States Minor Outlying Islands'},
  {id: 858, name: 'Uruguay'},
  {id: 860, name: 'Uzbekistan'},
  {id: 548, name: 'Vanuatu'},
  {id: 862, name: 'Venezuela, Bolivarian Republic of'},
  {id: 704, name: 'Viet Nam'},
  {id: 92, name: 'Virgin Islands, British'},
  {id: 850, name: 'Virgin Islands, U.S.'},
  {id: 876, name: 'Wallis and Futuna'},
  {id: 732, name: 'Western Sahara'},
  {id: 887, name: 'Yemen'},
  {id: 894, name: 'Zambia'},
  {id: 716, name: 'Zimbabwe'},
];

const TIME_ZONES = [
  {country: 'Pacific/Pago_Pago', name: '(GMT-11:00) Pago Pago', delta: -11},
  {country: 'Pacific/Honolulu', name: '(GMT-10:00) Hawaii', delta: -10},
  {country: 'America/Anchorage', name: '(GMT-9:00) Alaska', delta: -9},
  {country: 'America/Juneau', name: '(GMT-9:00) Juneau', delta: -9},
  {country: 'America/Vancouver', name: '(GMT-8:00) Vancouver', delta: -8},
  {
    country: 'America/Los_Angeles',
    name: '(GMT-8:00) Pacific Time (US and Canada)',
    delta: -8,
  },
  {country: 'America/Tijuana', name: '(GMT-8:00) Tijuana', delta: -8},
  {country: 'America/Phoenix', name: '(GMT-7:00) Arizona', delta: -7},
  {country: 'America/Mazatlan', name: '(GMT-7:00) Mazatlan', delta: -7},
  {country: 'America/Chihuahua', name: '(GMT-7:00) Chihuahua', delta: -7},
  {country: 'America/Edmonton', name: '(GMT-7:00) Edmonton', delta: -7},
  {
    country: 'America/Denver',
    name: '(GMT-7:00) Mountain Time (US and Canada)',
    delta: -7,
  },
  {country: 'America/Regina', name: '(GMT-6:00) Saskatchewan', delta: -6},
  {country: 'America/Mexico_City', name: '(GMT-6:00) Mexico City', delta: -6},
  {country: 'America/Guatemala', name: '(GMT-6:00) Guatemala', delta: -6},
  {country: 'America/El_Salvador', name: '(GMT-6:00) El Salvador', delta: -6},
  {country: 'America/Managua', name: '(GMT-6:00) Managua', delta: -6},
  {country: 'America/Costa_Rica', name: '(GMT-6:00) Costa Rica', delta: -6},
  {country: 'America/Tegucigalpa', name: '(GMT-6:00) Tegucigalpa', delta: -6},
  {country: 'America/Monterrey', name: '(GMT-6:00) Monterrey', delta: -6},
  {country: 'America/Winnipeg', name: '(GMT-6:00) Winnipeg', delta: -6},
  {
    country: 'America/Chicago',
    name: '(GMT-6:00) Central Time (US and Canada)',
    delta: -6,
  },
  {country: 'America/Panama', name: '(GMT-5:00) Panama', delta: -5},
  {country: 'America/Bogota', name: '(GMT-5:00) Bogota', delta: -5},
  {country: 'America/Lima', name: '(GMT-5:00) Lima', delta: -5},
  {country: 'America/Montreal', name: '(GMT-5:00) Montreal', delta: -5},
  {
    country: 'America/New_York',
    name: '(GMT-5:00) Eastern Time (US and Canada)',
    delta: -5,
  },
  {
    country: 'America/Indianapolis',
    name: '(GMT-5:00) Indiana (East)',
    delta: -5,
  },
  {country: 'America/Puerto_Rico', name: '(GMT-4:00) Puerto Rico', delta: -4},
  {country: 'America/Caracas', name: '(GMT-4:00) Caracas', delta: -4},
  {country: 'America/La_Paz', name: '(GMT-4:00) La Paz', delta: -4},
  {country: 'America/Guyana', name: '(GMT-4:00) Guyana', delta: -4},
  {country: 'America/Halifax', name: '(GMT-4:00) Halifax', delta: -4},
  {
    country: 'Canada/Atlantic',
    name: '(GMT-4:00) Atlantic Time (Canada)',
    delta: -4,
  },
  {
    country: 'America/St_Johns',
    name: '(GMT-3:30) Newfoundland and Labrador',
    delta: -3.5,
  },
  {country: 'America/Santiago', name: '(GMT-3:00) Santiago', delta: -3},
  {country: 'America/Montevideo', name: '(GMT-3:00) Montevideo', delta: -3},
  {country: 'America/Araguaina', name: '(GMT-3:00) Recife', delta: -3},
  {
    country: 'America/Argentina/Buenos_Aires',
    name: '(GMT-3:00) Buenos Aires, Georgetown',
    delta: -3,
  },
  {country: 'America/Godthab', name: '(GMT-3:00) Greenland', delta: -3},
  {country: 'America/Sao_Paulo', name: '(GMT-3:00) Sao Paulo', delta: -3},
  {country: 'Atlantic/Azores', name: '(GMT-1:00) Azores', delta: -1},
  {
    country: 'Atlantic/Cape_Verde',
    name: '(GMT-1:00) Cape Verde Islands',
    delta: -1,
  },
  {country: 'UTC', name: '(GMT+0:00) Universal Time UTC', delta: 0},
  {country: 'Etc/Greenwich', name: '(GMT+0:00) Greenwich Mean Time', delta: 0},
  {country: 'Atlantic/Reykjavik', name: '(GMT+0:00) Reykjavik', delta: 0},
  {country: 'Europe/Dublin', name: '(GMT+0:00) Dublin', delta: 0},
  {country: 'Europe/London', name: '(GMT+0:00) London', delta: 0},
  {country: 'Europe/Lisbon', name: '(GMT+0:00) Lisbon', delta: 0},
  {country: 'Africa/Nouakchott', name: '(GMT+0:00) Nouakchott', delta: 0},
  {
    country: 'Europe/Belgrade',
    name: '(GMT+1:00) Belgrade, Bratislava, Ljubljana',
    delta: 1,
  },
  {country: 'CET', name: '(GMT+1:00) Sarajevo, Skopje, Zagreb', delta: 1},
  {country: 'Africa/Casablanca', name: '(GMT+1:00) Casablanca', delta: 1},
  {country: 'Europe/Oslo', name: '(GMT+1:00) Oslo', delta: 1},
  {country: 'Europe/Copenhagen', name: '(GMT+1:00) Copenhagen', delta: 1},
  {country: 'Europe/Brussels', name: '(GMT+1:00) Brussels', delta: 1},
  {
    country: 'Europe/Berlin',
    name: '(GMT+1:00) Amsterdam, Berlin, Rome, Stockholm, Vienna',
    delta: 1,
  },
  {country: 'Europe/Amsterdam', name: '(GMT+1:00) Amsterdam', delta: 1},
  {country: 'Europe/Rome', name: '(GMT+1:00) Rome', delta: 1},
  {country: 'Europe/Stockholm', name: '(GMT+1:00) Stockholm', delta: 1},
  {country: 'Europe/Vienna', name: '(GMT+1:00) Vienna', delta: 1},
  {country: 'Europe/Luxembourg', name: '(GMT+1:00) Luxembourg', delta: 1},
  {country: 'Europe/Paris', name: '(GMT+1:00) Paris', delta: 1},
  {country: 'Europe/Zurich', name: '(GMT+1:00) Zurich', delta: 1},
  {country: 'Europe/Madrid', name: '(GMT+1:00) Madrid', delta: 1},
  {country: 'Africa/Bangui', name: '(GMT+1:00) West Central Africa', delta: 1},
  {country: 'Africa/Algiers', name: '(GMT+1:00) Algiers', delta: 1},
  {country: 'Africa/Tunis', name: '(GMT+1:00) Tunis', delta: 1},
  {country: 'Europe/Warsaw', name: '(GMT+1:00) Warsaw', delta: 1},
  {country: 'Europe/Prague', name: '(GMT+1:00) Prague Bratislava', delta: 1},
  {country: 'Europe/Budapest', name: '(GMT+1:00) Budapest', delta: 1},
  {country: 'Europe/Helsinki', name: '(GMT+2:00) Helsinki', delta: 2},
  {country: 'Africa/Harare', name: '(GMT+2:00) Harare, Pretoria', delta: 2},
  {country: 'Europe/Sofia', name: '(GMT+2:00) Sofia', delta: 2},
  {country: 'Europe/Athens', name: '(GMT+2:00) Athens', delta: 2},
  {country: 'Europe/Bucharest', name: '(GMT+2:00) Bucharest', delta: 2},
  {country: 'Asia/Nicosia', name: '(GMT+2:00) Nicosia', delta: 2},
  {country: 'Asia/Beirut', name: '(GMT+2:00) Beirut', delta: 2},
  {country: 'Asia/Jerusalem', name: '(GMT+2:00) Jerusalem', delta: 2},
  {country: 'Africa/Tripoli', name: '(GMT+2:00) Tripoli', delta: 2},
  {country: 'Africa/Cairo', name: '(GMT+2:00) Cairo', delta: 2},
  {country: 'Africa/Johannesburg', name: '(GMT+2:00) Johannesburg', delta: 2},
  {country: 'Africa/Khartoum', name: '(GMT+2:00) Khartoum', delta: 2},
  {country: 'Europe/Kiev', name: '(GMT+2:00) Kiev', delta: 2},
  {country: 'Asia/Damascus', name: '(GMT+2:00) Damascus', delta: 2},
  {country: 'Asia/Amman', name: '(GMT+2:00) Amman', delta: 2},
  {country: 'Africa/Nairobi', name: '(GMT+3:00) Nairobi', delta: 3},
  {country: 'Europe/Istanbul', name: '(GMT+3:00) Istanbul', delta: 3},
  {country: 'Europe/Moscow', name: '(GMT+3:00) Moscow', delta: 3},
  {country: 'Asia/Baghdad', name: '(GMT+3:00) Baghdad', delta: 3},
  {country: 'Asia/Kuwait', name: '(GMT+3:00) Kuwait', delta: 3},
  {country: 'Asia/Riyadh', name: '(GMT+3:00) Riyadh', delta: 3},
  {country: 'Asia/Bahrain', name: '(GMT+3:00) Bahrain', delta: 3},
  {country: 'Asia/Qatar', name: '(GMT+3:00) Qatar', delta: 3},
  {country: 'Asia/Aden', name: '(GMT+3:00) Aden', delta: 3},
  {country: 'Africa/Djibouti', name: '(GMT+3:00) Djibouti', delta: 3},
  {country: 'Africa/Mogadishu', name: '(GMT+3:00) Mogadishu', delta: 3},
  {country: 'Europe/Minsk', name: '(GMT+3:00) Minsk', delta: 3},
  {country: 'Asia/Tehran', name: '(GMT+3:30) Tehran', delta: 3.5},
  {country: 'Asia/Dubai', name: '(GMT+4:00) Dubai', delta: 4},
  {country: 'Asia/Muscat', name: '(GMT+4:00) Muscat', delta: 4},
  {country: 'Asia/Baku', name: '(GMT+4:00) Baku, Tbilisi, Yerevan', delta: 4},
  {country: 'Asia/Kabul', name: '(GMT+4:30) Kabul', delta: 4.5},
  {country: 'Asia/Yekaterinburg', name: '(GMT+5:00) Yekaterinburg', delta: 5},
  {
    country: 'Asia/Tashkent',
    name: '(GMT+5:00) Islamabad, Karachi, Tashkent',
    delta: 5,
  },
  {country: 'Asia/Calcutta', name: '(GMT+5:30) India', delta: 5.5},
  {
    country: 'Asia/Kolkata',
    name: '(GMT+5:30) Mumbai, Kolkata, New Delhi',
    delta: 5.5,
  },
  {country: 'Asia/Kathmandu', name: '(GMT+5:45) Kathmandu', delta: 5.75},
  {country: 'Asia/Almaty', name: '(GMT+6:00) Almaty', delta: 6},
  {country: 'Asia/Dacca', name: '(GMT+6:00) Dacca', delta: 6},
  {country: 'Asia/Dhaka', name: '(GMT+6:00) Astana, Dhaka', delta: 6},
  {country: 'Asia/Rangoon', name: '(GMT+6:30) Rangoon', delta: 6.5},
  {country: 'Asia/Novosibirsk', name: '(GMT+7:00) Novosibirsk', delta: 7},
  {country: 'Asia/Krasnoyarsk', name: '(GMT+7:00) Krasnoyarsk', delta: 7},
  {country: 'Asia/Bangkok', name: '(GMT+7:00) Bangkok', delta: 7},
  {country: 'Asia/Saigon', name: '(GMT+7:00) Vietnam', delta: 7},
  {country: 'Asia/Jakarta', name: '(GMT+7:00) Jakarta', delta: 7},
  {country: 'Asia/Irkutsk', name: '(GMT+8:00) Irkutsk, Ulaanbaatar', delta: 8},
  {country: 'Asia/Shanghai', name: '(GMT+8:00) Beijing, Shanghai', delta: 8},
  {country: 'Asia/Hong_Kong', name: '(GMT+8:00) Hong Kong SAR', delta: 8},
  {country: 'Asia/Taipei', name: '(GMT+8:00) Taipei', delta: 8},
  {country: 'Asia/Kuala_Lumpur', name: '(GMT+8:00) Kuala Lumpur', delta: 8},
  {country: 'Asia/Singapore', name: '(GMT+8:00) Singapore', delta: 8},
  {country: 'Australia/Perth', name: '(GMT+8:00) Perth', delta: 8},
  {country: 'Asia/Yakutsk', name: '(GMT+9:00) Yakutsk', delta: 9},
  {country: 'Asia/Seoul', name: '(GMT+9:00) Seoul', delta: 9},
  {country: 'Asia/Tokyo', name: '(GMT+9:00) Osaka, Sapporo, Tokyo', delta: 9},
  {country: 'Australia/Darwin', name: '(GMT+9:30) Darwin', delta: 9.5},
  {country: 'Asia/Vladivostok', name: '(GMT+10:00) Vladivostok', delta: 10},
  {
    country: 'Pacific/Port_Moresby',
    name: '(GMT+10:00) Guam, Port Moresby',
    delta: 10,
  },
  {country: 'Australia/Brisbane', name: '(GMT+10:00) Brisbane', delta: 10},
  {country: 'Australia/Adelaide', name: '(GMT+10:30) Adelaide', delta: 10.5},
  {
    country: 'Australia/Sydney',
    name: '(GMT+11:00) Canberra, Melbourne, Sydney',
    delta: 11,
  },
  {country: 'Australia/Hobart', name: '(GMT+11:00) Hobart', delta: 11},
  {country: 'Asia/Magadan', name: '(GMT+11:00) Magadan', delta: 11},
  {country: 'SST', name: '(GMT+11:00) Solomon Islands', delta: 11},
  {country: 'Pacific/Noumea', name: '(GMT+11:00) New Caledonia', delta: 11},
  {country: 'Asia/Kamchatka', name: '(GMT+12:00) Kamchatka', delta: 12},
  {
    country: 'Pacific/Fiji',
    name: '(GMT+12:00) Fiji Islands, Marshall Islands',
    delta: 12,
  },
  {
    country: 'Pacific/Auckland',
    name: '(GMT+13:00) Auckland, Wellington',
    delta: 13,
  },
  {
    country: 'Pacific/Apia',
    name: '(GMT+14:00) Independent State of Samoa',
    delta: 14,
  },
];

export {COUNTRIES, TIME_ZONES};
